#### Stage 1 ####
FROM oven/bun:latest AS builder

# Copy and set directory
COPY . /var/www/html
WORKDIR /var/www/html

ENV NODE_OPTIONS=--max-old-space-size=8192
ENV NITRO_PRESET=node_cluster

# Install deps and cache image layer
RUN bun install
# Build project and cache image layer

ENV NODE_ENV=production
RUN bun run build
########

#### Stage 2 ####
FROM oven/bun:latest AS prod

WORKDIR /var/www/html

COPY --from=builder  /var/www/html/.output  ./.output
COPY --from=builder  /var/www/html/ecosystem.config.cjs ./ecosystem.config.cjs

# All ready now
EXPOSE 3000

ARG GIT_VERSION_HASH
ENV NUXT_PUBLIC_COMMIT_HASH=${GIT_VERSION_HASH}
ENV NODE_ENV=production

HEALTHCHECK CMD curl --fail http://localhost:3000 || exit 1

RUN bun global install pm2

CMD ["pm2-runtime", "ecosystem.config.cjs"]
