#### Stage 1 ####
FROM denoland/deno:2.0.0 AS builder

# Copy and set directory
COPY . /var/www/html
WORKDIR /var/www/html

ENV NODE_OPTIONS="--max-old-space-size=16384"

# Install deps and cache image layer
RUN echo $NODE_OPTIONS

RUN deno install
# Build project and cache image layer
RUN deno run build
########

#### Stage 2 ####
FROM denoland/deno:2.0.0 AS prod

WORKDIR /var/www/html

COPY --from=builder  /var/www/html/.output  ./.output
COPY --from=builder  /var/www/html/ecosystem.config.js ./ecosystem.config.js

# All ready now
EXPOSE 3000

ARG GIT_VERSION_HASH
ENV NITRO_PRESET=deno_server
ENV NUXT_PUBLIC_COMMIT_HASH=${GIT_VERSION_HASH}

RUN deno run -Ar jsr:@pup/pup setup

# CMD ["pm2-runtime", "ecosystem.config.js"]
CMD pup run --config pup.json