#### DEV ####
FROM denoland/deno:2.0.0 AS dev

WORKDIR /var/www/html
EXPOSE 3000

COPY . /var/www/html

# Install deps and Run
CMD ["/bin/sh", "-c", "deno install && rm -rf /tmp/nitro && deno run dev"]
