#### DEV ####
FROM node:18-bookworm-slim as dev

WORKDIR /var/www/html
EXPOSE 3000

COPY ./root /var/www/html

# install deps and cache image layer
RUN yarn
# Run (Ensure previous worker is deleted if exists)
CMD ["/bin/sh", "-c", "rm -rf /tmp/nitro && yarn dev"]
