// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxtjs/color-mode" />
/// <reference types="nuxt-windicss" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="cookie-universal-nuxt" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxt/image" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
export {}
